### ISSUE TITLE
Invalid option --no-progress-meter

### ISSUE THREAD

**Issue by kevinvangelder** [stevenharman/heroku-buildpack-pdftk-java-native#1]
```shell
curl: option --no-progress-meter: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
 !     Push rejected, failed to compile pdftk-java-native app.
 !     Push failed
 ```

**Comment by kevinvangelder** [comment]
It turned out that because I wasn't explicitly specifying the stack in `app.json` for my review apps it fell back to `heroku-18`. Explicitly specifying `"stack": "heroku-22"` resolved this build error.

**Comment by stevenharman** [comment]
Ah! So the problem is that the [`curl` that ships with `heroku-18`](https://devcenter.heroku.com/articles/stack-packages) is old enough (`7.58.0-2ubuntu3.22`) that it doesn't support the `--no-progress-meter` option, which [was added in `7.67.0`](https://curl.se/changes.html#7_67_0).

Since `heroku-18` is deprecated and set to EoL in April of this year, I'm not going to worry about it. But thank you for reporting.

**Comment by kevinvangelder** [comment]
Yes, no changes expected, just wanted to document in case other users ran into the same or similar errors.
